services:
  backpipe:
    user: "1000:1000"
    image: reaktivnii/backpipe:latest
    container_name: backpipe
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: -s -i /input -o /output -c /app/config.cfg
    cpus: '4.0'
    mem_limit: 10g
    mem_reservation: 4g
    volumes:
      - ./input:/input
      - ./output:/output
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "container_name=backpipe,service=backpipe"
        labels: "job"
        env: "env"
        keep-file: "false"
    restart: unless-stopped
    tty: true

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --label-enable backpipe

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    cpus: '0.5'
    mem_limit: 1g
    mem_reservation: 256m
    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    cpus: '0.5'
    mem_limit: 512m
    mem_reservation: 128m
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
